### ISSUE TITLE
Better detection

### ISSUE THREAD

**Issue by rderimay** [cmanley/PHP-MagickLite#2]
Hi there, thanks for the good work.

Lines 114 and 130

To me, it would be better to have the detection of the presence of the CLIs done on the CLIs themselves instead of using ```which```. In fact, the user under which the PHP script is running can very well have the rights to run the CLIs but **not** to run the ```which``` command. (It was my case)
In that case, the detection will fail even if running ```gm``` or ```identify``` would have worked.

I would replace both line with:

```
			$cmd = exec('gm version', $out, $rc);
```
and
```
			$cmd = exec('identify -version', $out, $rc);
```

**Comment by cmanley** [comment]
Yes I agree and fixed it.
